name: Crowdin Action

on:
  push:
    branches: [ 12-add-translations ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3.11 -m pip install Flask-Babel
          pybabel extract -F sketch_map_tool/config/babel.cfg -o messages.pot .
      - name: Sync GH and Crowdin
        uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin
          create_pull_request: true
          push_sources: false
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
